title: Oniro
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://Yueqi77-amazing/eclipse-oniro4openharmony.github.io

aux_links:
  Template Repository: https://github.com/Yueqi77-amazing/eclipse-oniro4openharmony.github.io
